Creating a pull request for code reviewing
menyagah/youTube_clone pull request #10
Opened 2020-01-22 10:03 UTC by menyagah

2020-01-22 10:29 UTC, nikasulo requested changes
# Under Review by Oluwadamilare Tolulope Olusakin(TSE)
Great work @menyagah and @Morrism1. I am currently writing your review and will be done within the hour, please check on it in a few minutes :+1:

2020-01-22 10:55 UTC, nikasulo requested changes
# Nice work team! @menyagah and @Morrism1 
This is really fantastic all together! Great job :handshake:. Just one tiny issue to address and you can wrap up here :smiley:, please see my comments below.

#### Descriptive PR
You need a more descriptive PR as it is a hard requirement. Consider describing the work you have completed in the branch in as much detail as you can and even include a link to the live project to speed up your review!
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-01-22 10:55 UTC, Oluwadamilareolusakin commented on index.html
> +    <link rel="stylesheet" href="css/style.css" />
#### [OPTIONAL]
Consider loading up your css file before the font files so your page can look great immediately the file is served. Font files can take a bit of time to load up especially with slower internet connections and mobile devices! :+1:

2020-01-22 12:45 UTC, menyagah commented
Thank you so much for the review! Much appreciated! One question though,
you have pointed out on the Pull Requests issue. Kindly if I may ask do you
recommend that we go back and make them more descriptive or is this a
recommendation for our future projects? Much appreciated for the
quick response and outstanding delivery.

On Wed, 22 Jan 2020 at 13:55, Tolulope Oluwadamilare Olusakin <
notifications@github.com> wrote:

> *@Oluwadamilareolusakin* requested changes on this pull request.
> Nice work team! @menyagah <https://github.com/menyagah> and @Morrism1
> <https://github.com/Morrism1>
>
> This is really fantastic all together! Great job 🤝. Just one tiny issue
> to address and you can wrap up here 😃, please see my comments below.
> Descriptive PR
>
> You need a more descriptive PR as it is a hard requirement. Consider
> describing the work you have completed in the branch in as much detail as
> you can and even include a link to the live project to speed up your review!
> [image: screenshot]
> <https://camo.githubusercontent.com/3214000760c8b4ab2b11aa4a67276035c3c77ff1/68747470733a2f2f6769746c61622e636f6d2f6d6963726f76657273652f6775696465732f70726f6a656374732f726571756972656d656e74735f73637265656e73686f74732f7261772f6d61737465722f696d616765732f67656e6572616c2f64657363726970746976655f7072732e706e67>
> Think I missed something? Need some help with this or any of your
> projects? Please feel free to reach out to me on Twitter
> <https://twitter.com/oluwadamilareo_> or Instagram
> <https://instagram.com/oluwadamilare_olusakin>, even if you just want to
> chat and I will respond to you as soon as I can.
> ------------------------------
>
> In index.html
> <https://github.com/menyagah/youTube_clone/pull/10#discussion_r369492665>:
>
> > +    <meta charset="UTF-8" />
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>
> +    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
>
> +    <link
>
> +      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
>
> +      rel="stylesheet"
>
> +    />
>
> +    <link
>
> +      href="https://fonts.googleapis.com/icon?family=Material+Icons"
>
> +      rel="stylesheet"
>
> +    />
>
> +    <link
>
> +      href="https://fonts.googleapis.com/css?family=Roboto&display=swap"
>
> +      rel="stylesheet"
>
> +    />
>
> +    <link rel="stylesheet" href="css/style.css" />
>
>
> [OPTIONAL]
>
> Consider loading up your css file before the font files so your page can
> look great immediately the file is served. Font files can take a bit of
> time to load up especially with slower internet connections and mobile
> devices! 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/menyagah/youTube_clone/pull/10?email_source=notifications&email_token=AFY6OKTSVAECJYHK5TP7QOTQ7AQ3LA5CNFSM4KKC6IJ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCSTSZEI#pullrequestreview-346500241>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFY6OKXLZIT2X6VFZWR46TDQ7AQ3LANCNFSM4KKC6IJQ>
> .
>

2020-01-23 19:13 UTC, mosesogwo approved these changes
**Hi team, Good work :+1:. Your project is approved.**

In future projects, also use descriptive titles for your pull request. For example, this current pull request title could be "Youtube Clone - Complete feature".

You may now merge to master.

**Cheers :smile:**

**Status: Approved!**

2020-01-23 19:13 UTC, merged